{% set name = "python-suitesparse-graphblas" %}
{% set version = "8.0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/suitesparse-graphblas/suitesparse-graphblas-{{ version }}.tar.gz
  sha256: 7d0f7fdded70d549800a4ba3d9b6ed4cb17980c3de1c2d3a1861880100a72ef3

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=64
    - setuptools-git-versioning
    - cffi
    - cython
    - graphblas ={{ version.rsplit('.', 1)[0] }}
    - numpy
    - pytest-runner
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - cffi

test:
  imports:
    - suitesparse_graphblas
  commands:
    - pip check
    - python -c "import platform ; print(platform.machine())"
    - python -c "from suitesparse_graphblas import lib, ffi"
    - pytest -v --pyargs suitesparse_graphblas
  requires:
    - pip
    - pytest

about:
  home: https://github.com/GraphBLAS/python-suitesparse-graphblas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python CFFI binding around SuiteSparse::GraphBLAS
  description: |
    Python CFFI binding around SuiteSparse::GraphBLAS. This is a base package that exposes
    only the low level CFFI API bindings and symbols. This package is shared by the syntax
    bindings pygraphblas and python-graphblas.
  dev_url: https://github.com/GraphBLAS/python-suitesparse-graphblas

extra:
  recipe-maintainers:
    - jim22k
    - eriknw
    - michelp
